# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'coolmeiappxcode' do
  
  pod 'PBJHexagon'

  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for coolmeiappxcode

  target 'coolmeiappxcodeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'coolmeiappxcodeUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
