# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'teste CocoaPod' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for teste CocoaPod

  pod 'PBJHexagon'

  target 'teste CocoaPodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'teste CocoaPodUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
